Models/ContactUs.cs
using MyLodge.proj1.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Raven.Client.Documents;
using Raven.Client.Documents.Session;
using System.ComponentModel.DataAnnotations;
namespace MyLodge.proj1.Models
{
    public class ContactUs
    {
        [Newtonsoft.Json.JsonIgnore]
        Utils.RavenDBConnector raven = Utils.RavenDBConnector.Instance();
        [Newtonsoft.Json.JsonIgnore]
        private string className;
        public int Contactid { get; set; }
        [Required]
        public string Name { get; set; }
       
        public string Email { get; set; }
        public string Message { get; set; }

        public ContactUs()
        {
            this.className = this.GetType().Name;
        }
        public ContactUs(string className)
        {
            this.className = className;
        }
        public ContactUs(int Contactid, string Name, string Email, string Message) : this(Name)
        {
            this.Contactid = Contactid;
            this.Name = Name;
            this.Message = Message;
            this.Email = Email;
           
        }
        public int GetContactid()
        {
            return Contactid;
        }
        public string GetName()
        {
            return Name;
        }

        public void Save()
        {
            this.Contactid = GetNewPK();
            raven.SaveDocument(this.GetType().Name + "/" + Contactid, this);
        }
        public ContactUs Read(int i)
        {
            return raven.ReadDocument<ContactUs>(className + "/" + i);
        }
        public int GetNewPK()
        {
            ContactUs obj = new ContactUs();
            int i = 0;
            try
            {
                bool infinite = true;
                while (infinite)
                {

                    if (!(Read(i) is null))
                    {
                        obj = raven.ReadDocument<ContactUs>(this.GetType().Name + "/" + i);
                        i++;
                    }
                    else
                    {
                        return i;
                        //break;
                    }
                }
            }
            catch (NullReferenceException)
            {

            }
            return i;
        }


        public List<ContactUs> GetAllContactus()
        {

            List<ContactUs> listmember = new List<ContactUs>();
            ContactUs obj = new ContactUs();
            bool infinite = true;
            int i = 0;
            while (infinite)
            {

                if (!(Read(i) is null))
                {
                    obj = raven.ReadDocument<ContactUs>(className + "/" + i);

                    listmember.Add(obj);
                    i++;
                }
                else
                {
                    return listmember;
                }
            }
            return listmember;
        }
       
        public ContactUs GetCustomerByCusid(int cusid)
        {
            List<ContactUs> c = new List<ContactUs>();
            c = raven.QueryWhere<ContactUs>(x => x.Contactid == cusid).ToList();
            try
            {
                if (c[0] is null)
                {
                    return null;
                }
            }
            catch (IndexOutOfRangeException)
            {
                return null;
            }
            catch (ArgumentOutOfRangeException)
            {
                return null;
            }
            return c[0];
        }

      
      
        //GetAllMemberNic
        public List<string> GetCName()
        {
            List<ContactUs> hr = new List<ContactUs>();
            hr = this.GetAllContactus();

            return hr.Select(c => c.Name).ToList();
        }

        //GetAllMemberCountry
        public List<string> GetCEmail()
        {
            List<ContactUs> hr = new List<ContactUs>();
            hr = this.GetAllContactus();

            return hr.Select(c => c.Email).ToList();
        }

        //GetAllMemberAddress
        public List<string> GetMessage()
        {
            List<ContactUs> hr = new List<ContactUs>();
            hr = this.GetAllContactus();

            return hr.Select(c => c.Message).ToList();
        }
        

        public void Delete(int i)
        {
            raven.DeleteDocument(className + "/" + i);
        }


        //add
    }
}

Controllers/AuraChatFaqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using MyLodge.proj1.Areas.Admin.Controllers;
using MyLodge.proj1.Areas.Admin.Models.CSM;
using MyLodge.proj1.Models.Aura;
using MyLodge.proj1.Utils;
using Newtonsoft.Json;

namespace MyLodge.proj1.Controllers
{   
    public class AuraChatFaqController : Controller
    {
        SysDiagDebug d = new SysDiagDebug();
        [HttpGet]
        public IActionResult Chat()
        {
            AuraStats astats = new AuraStats();
            astats = astats.Read();//loads aura stats
            HttpContext.Session.SetObject("chatModel", null);
            if (!astats.AuraSystemOn)
            {
                //aura turned off
                return View("~/Views/Reservation/ContactUs.cshtml");
            }
            var chatModel = new AuraUserChat();
            //List<string> chatHistory = new List<string>();
            chatModel.chatHistory.Add("r:Hello! This is "+Aura.Name+", how can I help you?");
            d.Out(chatModel.ToString());
            HttpContext.Session.SetObject("chatModel", chatModel);
            HttpContext.Session.SetObject("auraModel", null);
            ViewBag.Collection = chatModel.chatHistory;
            return View("~/Views/Aura/Chat.cshtml");
        }
        [HttpPost]
        [HttpGet]
        public IActionResult GetResult(string msg)
        {
            SysDiagDebug d = new SysDiagDebug();
            var chatModel = new AuraUserChat();
            chatModel = HttpContext.Session.GetObject<AuraUserChat>("chatModel");
            //d.Out(chatModel.ToString());
            _ = new Aura();
            Aura aura;
            if (HttpContext.Session.GetObject<Aura>("auraModel") is null)
            {
                d.Out("auraModel is null! setting new instance using chatModel!");
                aura = new Aura(chatModel);
                HttpContext.Session.SetObject("auraModel", aura); //instance
            }
            else
            {
                aura = HttpContext.Session.GetObject<Aura>("auraModel");
                d.Out("auraModel is NOT null!");
                d.Out("auraModel.logCreated -> " + aura.logCreated);
                //d.Out("auraModel.waitForReply -> " + aura.waitForReply);
            }
            //Boolean hasSpam = aura.IsSpam(msg);
            string username = HttpContext.Session.GetString("username");
            if(username is null)
            {
                username = "000";//default
            }
            else
            {
                aura.SetUsername(username);
            }
            
            //d.Out("AuraChat>>username -> " + username);
            if (msg.Equals("End") || aura.endChat)
            {
                //Boolean repeat = false;
                string prev_msg1 = chatModel.chatHistory[chatModel.chatHistory.Count - 1];
                if (prev_msg1 != ("p:" + msg))
                {
                    d.Out("AuraChat>>chatHistory::Added -> " + msg);
                    chatModel.chatHistory.Add("p:" + msg);//person
                }
                HttpContext.Session.SetObject("auraModel", null); //instance to null
                aura.AuraEndProcess(chatModel);//passing due to instance being null sometimes
                return View("~/Views/Home/HotelHome.cshtml");
            }
            //Boolean repeat = false;
            string prev_msg = "";
            if (aura.waitForReply)
            {
                prev_msg = chatModel.chatHistory[chatModel.chatHistory.Count - 2];
            }
            else
            {
               prev_msg = chatModel.chatHistory[chatModel.chatHistory.Count - 1];
            }
            d.Out("AuraChat>>" + prev_msg);
            if (!prev_msg.Contains(msg))
            {
                d.Out("AuraChat>>chatHistory::Added -> " + msg);
                chatModel.chatHistory.Add("p:" + msg);//person
            }
            //if don't wait for reply
            if (!aura.waitForReply)
            {
                d.Out("Aura>>Processing msg!");
                if (aura.GenerateReply(msg) == "xf001")
                {
                    aura.SetAsForwarded();
                    chatModel.chatHistory.Add("r:" + "Hold on a moment!");
                    aura.AuraSaveChatLog(chatModel);
                    ViewBag.setToRefresh = "<meta http-equiv=\"refresh\" content=\"30\"/>";
                    d.Out("AuraChat>>catched xf001 => setting forward to TRUE!");
                }
                else
                {
                    d.Out("AuraChat>>Aura Processing..!");
                    chatModel.chatHistory.Add("r:" + aura.GenerateReply(msg));
                }
            }
            else
            {
                //check if csm handled the msg
                while (aura.waitForReply)
                {
                    //timeout and forwarded is handled   
                    if (aura.ForwardedIsHandled())
                    {
                        d.Out("AuraChat>>Forward is handled by CSM!");
                        chatModel.chatHistory.Add(aura.response);
                        aura.waitForReply = false;
                    }
                    else if ((DateTime.Now - aura.activated_time).Minutes > 1 || (DateTime.Now - aura.activated_time).Hours > 0)
                    {
                        //not handled within 1min
                        //d.Out("AuraChat>>Timeout waiting for reply!");
                        chatModel.chatHistory.Add("r:" + "Leave us your email, will try to reach back to you soon!");
                        aura.waitForReply = false;
                        aura.endChat = true;
                    }
                    //d.Out("AuraChat>>waitForReply -> " + aura.waitForReply);
                    //else wait for reply
                }
                ViewBag.setToRefresh = "<meta http-equiv=\"\" content=\"\"/>";
            } 
            HttpContext.Session.SetObject("auraModel", aura);
            HttpContext.Session.SetObject("chatModel", chatModel);
            ViewBag.Collection = chatModel.chatHistory;
            return View("~/Views/Aura/Chat.cshtml");
        }

        [HttpPost]
        [HttpGet]
        public IActionResult GetFAQPage()
        {
            FAQ_dataView faq = new FAQ_dataView();
            return View("~/Views/Aura/faq_page.cshtml",faq);
        }
    }
    
    public static class SessionExtensions
    {
        public static void SetObject(this ISession session, string key, object value)
        {
            session.SetString(key, JsonConvert.SerializeObject(value));
        }

        public static T GetObject<T>(this ISession session, string key)
        {
            var value = session.GetString(key);
            return value == null ? default(T) : JsonConvert.DeserializeObject<T>(value);
        }
    }
}

Views/Reservation/Hallshomepage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ }
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <style>
        .button {
            background-color: #4CAF50; /* Green */
            border: none;
            color: white;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }






        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }

        th, td {
            padding: 5px;
            text-align: left;
        }


        .img {
            height: 500px;
            width: 870px;
        }
    </style>

    <!-- CSS here -->
    <link rel="stylesheet" href="~/css/bootstrapss.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/gijgo.css">
    <link rel="stylesheet" href="~/css/slicknav.css">
    <link rel="stylesheet" href="~/css/animate.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/css/slick.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="~/css/responsive.css">
</head>
<body>

    <header>
        <!-- Header Start -->
        <div class="header-area header-sticky">
            <div class="main-header ">
                <div class="container">
                    <div class="row align-items-center">
                        <!-- logo -->
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo">
                                <a href="index.html">
                                    <img src="~/img/logo/m1.jpg" heigt="100" width="200" />
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-10">
                            <!-- main-menu -->
                            <div class="main-menu f-right d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="@Url.Action("Home", "Home") ">Home</a></li>

                                        <li>
                                            <a href="#">Reservation</a>
                                            <ul class="submenu">
                                                <li><a href="@Url.Action("Roomreserve", "Home") ">Room Reservation</a>
                                                <li><a href="@Url.Action("Hallreserve", "Home") ">Hall Reservation</a></li>

                                            </ul>
                                        </li>
                                        <li><a href="@Url.Action("AboutUs", "Home") ">About Us</a></li>
                                        <li><a href="@Url.Action("Chat", "AuraChatFaq") ">Contact Us</a></li>
                                        <li><a href="@Url.Action("GetFAQPage", "AuraChatFaq")">FAQ</a></li>
                                        <li><a href="@Url.Action("Signup", "Home") ">Sign Up</a></li>
                                        <li><a href="@Url.Action("UserProfile", "Home") ">User Profile</a></li>
                                        <li><a href="@Url.Action((string)ViewBag.log, "Home") ">@ViewBag.logbtn</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>

                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>
    <br />
    <section class="room-area">
        <div class="container">
            <center> <label style="font-size:30px"><b>Our Halls</b></label></center>
            <p>Lavish Hotel is a perfect wedding destination of any size that wants to embrace luxury and natural beauty. The hotel boasts up to 12 stunning venues, indoor and outdoor, with the lakeside garden is the most desirable. Upon arriving, you’ll suddenly feel the tranquil ambience, and you’ll realize that you’re far from the hustle and bustle of the capital city. The feeling of a tropical breeze, natures at every corner, and the calming view of the lake will calm your heart and mind as you say sacred vow to your loved one.</p>
            <p><b>We have 3 luxury halls available right now for you.</b></p><br />
            <div class="row justify-content-center">
                <div class="col-xl-8">

                    <!--font-back-tittle  -->
                    <div class="font-back-tittle mb-45">
                        <div class="archivment-front">

                        </div>
                        <h3 class="archivment-back">Our Rooms</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-4 col-lg-6 col-md-6">
                    <!-- Single Room -->
                    <div class="single-room mb-50">
                        <div class="room-img">
                            <a href="@Url.Action("Hall2", "Home") "><img src="~/img/halls/hall2.jpg" alt=""></a>
                        </div>
                        <div class="room-caption">
                            <h3><a href="@Url.Action("Hall2", "Home") ">Orchid</a></h3>
                            <div class="per-night">
                                <span><u>Rs</u>10000 </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 col-md-6">
                    <!-- Single Room -->
                    <div class="single-room mb-50">
                        <div class="room-img">
                            <a href="@Url.Action("Hall1", "Home") "><img src="~/img/halls/hall3.jpg" alt=""></a>
                        </div>
                        <div class="room-caption">
                            <h3><a href="@Url.Action("Hall1", "Home") ">Tulip</a></h3>
                            <div class="per-night">
                                <span><u>Rs</u>25000</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 col-md-6">
                    <!-- Single Room -->
                    <div class="single-room mb-50">
                        <div class="room-img">
                            <a href="@Url.Action("Hall3", "Home") "> <img src="~/img/halls/Lotushall.jpg" alt=""></a>
                        </div>
                        <div class="room-caption">
                            <h3><a href="@Url.Action("Hall3", "Home") ">lotus</a></h3>
                            <div class="per-night">
                                <span><u>Rs</u>45000 </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer>
        <!-- Footer Start-->
        <div class="footer-area black-bg footer-padding">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-30">
                            <!-- logo -->
                            <div class="footer-logo">
                                <a href="index.html">
                                    <img src="~/img/logo/l1.jpg" heigt="100" width="200" />
                                </a>
                            </div>
                            <div class="footer-social footer-social2">
                                <a href="#"><i class="fab fa-facebook-f"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fas fa-globe"></i></a>
                                <a href="#"><i class="fab fa-behance"></i></a>
                            </div>
                            <div class="footer-pera">
                                <p>
                                    Copyright &copy;
                                    <a>
                                        <script>document.write(new Date().getFullYear());</script> All rights reserved
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-5">
                        <div class="single-footer-caption mb-30">
                            <div class="footer-tittle">
                                <h4>Quick Links</h4>
                                <ul>
                                    <li><a href="#">About Lavish</a></li>
                                    <li><a href="#">Our Best Rooms</a></li>
                                    <li><a href="#">Hall Service</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3">
                        <div class="single-footer-caption mb-30">
                            <div class="footer-tittle">
                                <h4>Reservations</h4>
                                <ul>
                                    <li><a href="#">Tel: 0112707694</a></li>
                                    <li><a href="#">Skype: Lavishbooking</a></li>
                                    <li><a href="#">reservations@lavish.com</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4  col-sm-5">
                        <div class="single-footer-caption mb-30">
                            <div class="footer-tittle">
                                <h4>Our Location</h4>
                                <ul>
                                    <li><a href="#">198 west 21th Street,</a></li>
                                    <li><a href="#">Colombo 6</a></li>
                                </ul>
                                <!-- Form -->
                                <div class="footer-form">
                                    <div id="mc_embed_signup">
                                        <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                              method="get" class="subscribe_form relative mail_part">
                                            <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address"
                                                   class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                                                   onblur="this.placeholder = ' Email Address '">
                                            <div class="form-icon">
                                                <button type="submit" name="submit" id="newsletter-submit"
                                                        class="email_icon newsletter-submit button-contactForm">
                                                    <img src="~/img/logo/form-iocn.jpg" alt="">
                                                </button>
                                            </div>
                                            <div class="mt-10 info"></div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
</body>

Views/Reservation/Payment.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
            font-family: Arial;
            font-size: 17px;
            padding: 8px;
        }

        * {
            box-sizing: border-box;
        }

        .row {
            display: -ms-flexbox; /* IE10 */
            display: flex;
            -ms-flex-wrap: wrap; /* IE10 */
            flex-wrap: wrap;
            margin: 0 -16px;
        }

        .col-25 {
            -ms-flex: 25%; /* IE10 */
            flex: 25%;
        }

        .col-50 {
            -ms-flex: 50%; /* IE10 */
            flex: 50%;
        }

        .col-75 {
            -ms-flex: 75%; /* IE10 */
            flex: 75%;
        }

        .col-25,
        .col-50,
        .col-75 {
            padding: 0 16px;
        }

        .container {
            background-color: #f2f2f2;
            padding: 5px 20px 15px 20px;
            border: 1px solid lightgrey;
            border-radius: 3px;
        }

        input[type=text] {
            width: 100%;
            margin-bottom: 20px;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        label {
            margin-bottom: 10px;
            display: block;
        }

        .icon-container {
            margin-bottom: 20px;
            padding: 7px 0;
            font-size: 24px;
        }

        .button {
            background-color: #FF0000; /* Green */
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
        }

        .btn:hover {
            background-color: #45a049;
        }

        a {
            color: #2196F3;
        }

        hr {
            border: 1px solid lightgrey;
        }

        span.price {
            float: right;
            color: grey;
        }

        /* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other (also change the direction - make the "cart" column go on top) */

        .row {
            flex-direction: column-reverse;
        }

        .col-25 {
            margin-bottom: 20px;
        }
      
    </style>
</head>
<body>

    @{ Html.BeginForm("success", "Home", FormMethod.Post);
    }
    <form action="/action_page.php">
        <div class="col-50">
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <button class="btn btn-primary" id="demo" name="signup" onclick="demobtnpay()" style="background-color:purple">DEMO</button>

                    </div>
                </div>
            </div>
            <h3>Payment</h3>
            <label for="fname">Accepted Cards</label>
            <div class="icon-container">
                <i class="fa fa-cc-visa" style="color:navy;"></i>
                <i class="fa fa-cc-amex" style="color:blue;"></i>
                <i class="fa fa-cc-mastercard" style="color:red;"></i>
                <i class="fa fa-cc-discover" style="color:orange;"></i>
            </div>
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="John More Doe" required>
            <label for="ccnum">Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444" required>
            <label for="expmonth">Exp Month</label>
            <input type="text" id="expmonth" name="expmonth" placeholder="September" required>
            <div class="row">
                <div class="col-50">
                    <label for="expyear">Exp Year</label>
                    <input type="text" id="expyear" name="expyear" placeholder="2018" required>
                </div>
                <div class="col-50">
                    <label for="cvv">CVV</label>
                    <input type="text" id="cvv" name="cvv" placeholder="352" required>
                </div>
             


            </div>
            <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
            Confrim payment
            <br /><br />

            <input type="submit" value="Reserve" class="button">
        </div>




    </form>

    <script>
        function demobtnpay() {
            document.getElementById("cname").value = "Vidura Sathsara";
            document.getElementById("ccnum").value = "5207-6356-2346-9256";
            document.getElementById("expmonth").value = "December";
            document.getElementById("expyear").value = "2022";
            document.getElementById("cvv").value = "698";
            

        }
    </script>


</body>
</html>
@{Html.EndForm();
}

Views/Reservation/Sucessful.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

    <html>
    <head>
        <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
    </head>
    <style>
        body {
            text-align: center;
            padding: 40px 0;
            background: #EBF0F5;
        }

        h1 {
            color: #88B04B;
            font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
            font-weight: 900;
            font-size: 40px;
            margin-bottom: 10px;
        }

        p {
            color: #404F5E;
            font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
            font-size: 20px;
            margin: 0;
        }

        i {
            color: #9ABC66;
            font-size: 100px;
            line-height: 200px;
            margin-left: -15px;
        }

        .card {
            background: white;
            padding: 60px;
            border-radius: 4px;
            box-shadow: 0 2px 3px #C8D0D8;
            display: inline-block;
            margin: 0 auto;
        }
    </style>
    <body>
        <div class="card">
            <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
                <i class="checkmark">✓</i>
            </div>
            <h1>Success</h1>
            <p>You reservation is succeesful;<br /> we are waiting for you!<br /><span style='font-size:100px;'>&#128525;</span></p>
            <a href="@Url.Action("Home", "Home") ">Back to Home</a>
            
        </div>
    </body>
    </html>