Areas/Admin/Models/Maintenance.cs
using FastMember;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace MyLodge.proj1.Areas.Admin.Models
{
    public class Maintenance
    {
        [Newtonsoft.Json.JsonIgnore]
        Utils.RavenDBConnector raven = Utils.RavenDBConnector.Instance();
        [Newtonsoft.Json.JsonIgnore]
        private string className;
        public int Maintenanceid { get; set; }
        public string RoomNo { get; set; }
        public string Items { get; set; }
        public string Toiletries { get; set; }
        public DateTime LcleanDate { get; set; }
        public DateTime NcleanDate { get; set; }

        public Maintenance()
        {
            this.className = this.GetType().Name;
        }
        public Maintenance(string className)
        {
            this.className = className;
        }

        public Maintenance(int Maintenanceid, string RoomNo, DateTime NcleanDate, DateTime LcleanDate, string Items, string Toiletrie) : this(RoomNo)
        {
            this.Maintenanceid = Maintenanceid;
            this.RoomNo = RoomNo;
            this.Items = Items;
            this.Toiletries = Toiletries;
            this.NcleanDate = NcleanDate;
            this.LcleanDate = LcleanDate;
        }
        //for csv        
        public override string ToString()
        {
            String newLine = "";
            if (Maintenanceid > 0)
            {
                newLine = "\n";
            }
            return newLine + Maintenanceid + "," + RoomNo + "," + Items + "," + Toiletries + "," + LcleanDate + "," + NcleanDate;
        }
        public List<int> GetMaintID()
        {
            List<Maintenance> hr = new List<Maintenance>();
            //hr = this.GetMint();
            hr = this.GetAllMaintenancedetails();
            hr.OrderByDescending(i => i.Maintenanceid);
            return hr.Select(Maintenance => Maintenance.Maintenanceid).ToList();
        }

        public List<Maintenance> GetMint()
        {
            return raven.QueryAll<Maintenance>();
        }

        public void Save()
        {
            this.Maintenanceid = GetNewPK();
            raven.SaveDocument(this.GetType().Name + "/" + Maintenanceid, this);
        }
        public Maintenance Read(int i)
        {
            return raven.ReadDocument<Maintenance>(className + "/" + i);
        }
        public int GetNewPK()
        {
            Maintenance obj = new Maintenance();
            int i = 0;
            try
            {
                bool infinite = true;
                while (infinite)
                {

                    if (!(Read(i) is null))
                    {
                        obj = raven.ReadDocument<Maintenance>(this.GetType().Name + "/" + i);
                        i++;
                    }
                    else
                    {
                        return i;
                        //break;
                    }
                }
            }
            catch (NullReferenceException)
            {

            }
            return i;
        }


        public List<Maintenance> GetAllMaintenancedetails()
        {

            return raven.QueryAll<Maintenance>();
        }


        //GetAllRoomNo
        public List<string> GetmemberReRoomNo()
        {
            List<Maintenance> hr = new List<Maintenance>();
            hr = this.GetAllMaintenancedetails();

            return hr.Select(Maintenance => Maintenance.RoomNo).ToList();
        }
        //GetAllMemberDOB
        public List<DateTime> GetmemberReLcleanDate()
        {
            List<Maintenance> hr = new List<Maintenance>();
            hr = this.GetAllMaintenancedetails();

            return hr.Select(Maintenance => Maintenance.LcleanDate).ToList();
        }
        //GetAllMemberDOB
        public List<DateTime> GetmemberReNcleanDate()
        {
            List<Maintenance> hr = new List<Maintenance>();
            hr = this.GetAllMaintenancedetails();

            return hr.Select(Maintenance => Maintenance.NcleanDate).ToList();
        }

        //GetAllMemberUserID
        public List<string> GetmemberReItems()
        {
            List<Maintenance> hr = new List<Maintenance>();
            hr = this.GetAllMaintenancedetails();

            return hr.Select(Maintenance => Maintenance.Items).ToList();
        }
        //GetAllMemberUserID
        public List<string> GetmemberReToiletries()
        {
            List<Maintenance> hr = new List<Maintenance>();
            hr = this.GetAllMaintenancedetails();

            return hr.Select(Maintenance => Maintenance.Toiletries).ToList();
        }



        //update
        public void UpdateMaintenance()
        {
            String[] variables = { "RoomNo", "Items", "Toiletries", "LcleanDate", "NcleanDate" };
            raven.UpdateDocument<Maintenance>(className + "/" + this.Maintenanceid, variables, this);
        }
        public void Delete(int i)
        {
            raven.DeleteDocument(className + "/" + i);
        }


        public Maintenance GetMintById(int maintenanceID)
        {
            List<Maintenance> c = new List<Maintenance>();
            c = raven.QueryWhere<Maintenance>(x => x.Maintenanceid == maintenanceID).ToList();
            try
            {
                if (c[0] is null)
                {
                    return null;
                }
            }
            catch (IndexOutOfRangeException)
            {
                return null;
            }
            catch (ArgumentOutOfRangeException)
            {
                return null;
            }
            return c[0];
        }

        public T SetAlternateCast<T>(T obj, int id)
        {
            var fieldNames = typeof(T).GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                            .Select(field => field.Name)
                            .ToList();
            dynamic thisClass = new Maintenance();
            Maintenance ar = new Maintenance();
            ar = ar.Read(id);
            thisClass = ObjectAccessor.Create(ar);
            //thisClass = thisClass.Read();

            for (int i = 0; i < fieldNames.Count; i++)
            {
                PropertyInfo Castproperty = obj.GetType().GetProperty(fieldNames[i]);
                //PropertyInfo Fromproperty = ar.GetType().GetProperty(fieldNames[i]);
                //d.Out("property->" + Castproperty.Name + " thisClass[" + i + "] -> " + thisClass[i]);
                Castproperty.SetValue(obj, thisClass[fieldNames[i]], null);
            }
            return obj;
        }
    }
}

Areas/Admin/Controllers/CusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyLodge.proj1.Areas.Admin.Models;
using Raven.Client.Documents;
using Raven.Client.Documents.Session;

namespace MyLodge.proj1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]")]
    public class CusController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, Route("Add")]
        public IActionResult Add()
        {
            return View("~/Areas/Admin/Views/Maintenance/addCustomerdata.cshtml");
        }

       

        [HttpPost]
        public IActionResult CusDetails()
        {
            return View("~/Areas/Admin/Views/Maintenance/addCustomerdata.cshtml");
        }

        [HttpPost]
        public IActionResult dash()
        {
            return View("~/Areas/Admin/Views/Maintenance/dashboard.cshtml");
        }


        [HttpPost, Route("Customer")]
        public IActionResult Customer(Customercheck hr)
        {
            hr.Save();
            CustomercheckView hrv = new CustomercheckView();
            // View("~/Views/Home/AdminCustomerMgt.cshtml", hrv);
            return View("~/Areas/Admin/Views/Maintenance/customerCheckin.cshtml", hrv);
            //return View("~/Areas/Admin/Views/Maintenance/addmaintenance.cshtml ", hrv); 
            //return View("~/Views/Maintenance/addmaintenance.cshtml",hrv);
        }


        [HttpPost, Route("ViewDashboard")]
        public IActionResult ViewDashboard()
        {
            CustomercheckView hrv = new CustomercheckView();
            return View("~/Areas/Admin/Views/Maintenance/customerCheckin.cshtml", hrv);
        }

        //search maintenance by id
        [HttpPost, Route("SearchMaint")]
        public IActionResult SearchMaint(String custId)  
        {

            Customercheck r = new Customercheck();
            CustomercheckView cv = new CustomercheckView();
            r = r.GetMintById(Int32.Parse(custId));

            cv.custId = r.custId;
            cv.custName = r.custName;
            cv.RoomNo = r.RoomNo;
            cv.phoneNo = r.phoneNo;
            cv.checkdate = r.checkdate;
            cv.checkOdate = r.checkOdate;

            if (r is null)
            {
                ViewBag.error = "Customer ID not found!";
                return View("~/Areas/Admin/Views/Maintenance/customerCheckin.cshtml");
            }
            else
            {

                return View("~/Areas/Admin/Views/Maintenance/customerCheckin.cshtml", cv);
            }
        }

        //navigate to update page
        [HttpPost, Route("EditMint")]
        public IActionResult EditMint(String id)
        {

            // HttpContext.Session.SetInt32("Maintenanceid", Int32.Parse(id));
            Customercheck r = new Customercheck();
            r = r.GetMintById(Int32.Parse(id));
            CustomercheckView hrv = new CustomercheckView();
            hrv = r.SetAlternateCast<CustomercheckView>(hrv, Int32.Parse(id));
            return View("~/Areas/Admin/Views/Maintenance/updateCustomer.cshtml", hrv);
        }


        // Upadate maintenance method
        [HttpPost, Route("UpdateMint")]
        [HttpGet]
        public IActionResult UpdateMint(Customercheck hr)
        {

            hr.UpdateCus();

            CustomercheckView st = new CustomercheckView();
            return View("~/Areas/Admin/Views/Maintenance/customerCheckin.cshtml", st);
        }

        //delete maintenance
        [HttpPost, Route("Delete")]
        [HttpGet]
        public IActionResult Delete(Customercheck s)
        {

            s.Delete(s.custId);
            CustomercheckView m = new CustomercheckView();
            return View("~/Areas/Admin/Views/Maintenance/customerCheckin.cshtml", m);

        }

        //generate report
        [HttpPost, Route("GetMintTableExcel")]
        public FileContentResult GetMintTableExcel()
        {
            Customercheck c = new Customercheck();
            List<Customercheck> cus = new List<Customercheck>();
            cus = c.GetAllCustomerdetails();
            string csv = String.Join(",", cus.Select(x => x.ToString()).ToArray());
            return File(new System.Text.UTF8Encoding().GetBytes(csv), "text/csv", "CustomrtCheckInList.csv");
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [HttpPost, Route("GetCusTable")]
        public IActionResult GetCusTable()
        {
            CustomercheckView cus = new CustomercheckView();
            return View("~/Areas/Admin/Views/Maintenance/addcustomerdata.cshtml", cus); //pass inherited class obj
        }
    }
    public class CustomercheckView : Customercheck
    {
        public CustomercheckView() : base("Customercheck")
        {

        }
    }


}

Areas/Admin/Controllers/MintController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyLodge.proj1.Areas.Admin.Models;
using MyLodge.proj1.Utils;
using Newtonsoft.Json;
using Raven.Client.Documents;
using Raven.Client.Documents.Session;

namespace MyLodge.proj1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]")]
    public class MintController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [HttpPost, Route("Add")]
        public IActionResult Add()
        {
            return View("~/Areas/Admin/Views/Maintenance/addmaintenance.cshtml");
        }

        //add maintenance
        [HttpGet]
        [HttpPost, Route("Maintenance")]
        public IActionResult Maintenance(Maintenance hr)
        {
            //hr.Save();
            MaintenanceView hrv = new MaintenanceView();
            return View("~/Areas/Admin/Views/Maintenance/roomMaintenance.cshtml", hrv);
        }

        [HttpGet]
        [HttpPost, Route("ViewDashboard")]
        public IActionResult ViewDashboard()
        {
            MaintenanceView hrv = new MaintenanceView();
            return View("~/Areas/Admin/Views/Maintenance/roomMaintenance.cshtml", hrv);
        }

        //search maintenance by id
        [HttpGet]
        [HttpPost, Route("SearchMaint")]
        public IActionResult SearchMaint(String Maintenanceid)
        {
            SysDiagDebug d = new SysDiagDebug("Mint>>");
            //d.Out("id -> " + Maintenanceid);
            MaintenanceView cv = new MaintenanceView();
            if (!(Maintenanceid is null))
            {
                Maintenance r = new Maintenance();
                r = r.GetMintById(int.Parse(Maintenanceid));

                if (r is null)
                {
                    ViewBag.error = "Maintenance ID not found!";
                    return View("~/Areas/Admin/Views/Maintenance/roomMaintenance.cshtml", cv);
                }
                else
                {
                    cv.Maintenanceid = r.Maintenanceid;
                    cv.RoomNo = r.RoomNo;
                    cv.Toiletries = r.Toiletries;
                    cv.Items = r.Items;
                    cv.LcleanDate = r.LcleanDate;
                    cv.NcleanDate = r.NcleanDate;
                    return View("~/Areas/Admin/Views/Maintenance/roomMaintenance.cshtml", cv);
                }
            }
            return View("~/Areas/Admin/Views/Maintenance/roomMaintenance.cshtml", cv);
        }

        //navigate to update page
        [HttpPost, Route("EditMint")]
        public IActionResult EditMint(String id)
        {

           // HttpContext.Session.SetInt32("Maintenanceid", Int32.Parse(id));
            Maintenance r = new Maintenance();
            r = r.GetMintById(Int32.Parse(id));
            MaintenanceView hrv = new MaintenanceView();
            hrv = r.SetAlternateCast<MaintenanceView>(hrv, Int32.Parse(id));
            return View("~/Areas/Admin/Views/Maintenance/updatemaintenance.cshtml", hrv);
        }


        // Upadate maintenance method
        [HttpPost, Route("UpdateMint")]
        [HttpGet]
        public IActionResult UpdateMint(Maintenance hr)
        {

            hr.UpdateMaintenance();

            MaintenanceView st = new MaintenanceView();
            return View("~/Areas/Admin/Views/Maintenance/roomMaintenance.cshtml", st);
        }

        //delete maintenance
        [HttpPost, Route("Delete")]
        [HttpGet]
        public IActionResult Delete(Maintenance s)
        {

            s.Delete(s.Maintenanceid);
            MaintenanceView m = new MaintenanceView();
            return View("~/Areas/Admin/Views/Maintenance/roomMaintenance.cshtml", m);

        }

        //generate report
        [HttpGet]
        [HttpPost, Route("GetMintTableExcel")]
        public FileContentResult GetMintTableExcel()
        {
            Maintenance c = new Maintenance();
            List<Maintenance> cus = new List<Maintenance>();
            cus = c.GetAllMaintenancedetails();
            string csv = String.Join(",", cus.Select(x => x.ToString()).ToArray());
            return File(new System.Text.UTF8Encoding().GetBytes(csv), "text/csv", "MaintenanceList.csv");
        }
        [HttpGet]
        [HttpPost, Route("GetMaintenanceTable")]
        public IActionResult GetMaintenanceTable()
        {
            MaintenanceView cus = new MaintenanceView();
            return View("~/Areas/Admin/Views/Maintenance/addmaintenance.cshtml", cus); //pass inherited class obj
        }

    }
    public class MaintenanceView : Maintenance
    {
        public MaintenanceView() : base("Maintenance")
        {

        }
    }

}

Areas/Admin/Views/Maintenance/addCustomerdata.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>

<html>

<head>

    <title>Add Customer</title>

    <link rel="stylesheet" href="~/css/add.css">

    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />

</head>

<body style=background-color:beige;>

    <img src="~/img/check1.jpg" align="right" width="500" height="400">

    <br>
    <div>
        @{ Html.BeginForm("Customer", "Cus", FormMethod.Post);
        }

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">

                        <div class="form-group">
                            <div class="col-md-9">
                                <label for="number">Customer Name :</label>
                                <input type="text" class="form-control" id="name" name="custName" placeholder="Enter the name">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-9">
                                <label for="number">Room Number : </label>
                                <input type="text" class="form-control" id="room" name="RoomNo" placeholder="Enter the room number"><br>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-9">
                                <label for="number">Phone Number : </label>
                                <input type="text" class="form-control" id="phone" name="phoneNo" placeholder="Enter the phone number"><br>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-9">
                                <label for="date3">Check In Date :</label><br><br>
                                <input type="date" class="form-control" id="date1" name="checkdate" placeholder="Enter the check-in date"><br><br>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-9">
                                <label for="date3">Check Out Date :</label><br><br>
                                <input type="date" class="form-control" id="date2" name="checkOdate" placeholder="Enter the check-out date"><br><br>
                            </div>
                        </div>
                    </div>






                    <input class="btn btn-primary" type="submit" value="Add Customer Check-In Details" name="add"> <br>
                </div>
            </div>
        </div>
    </div>
    </div>


    @{Html.EndForm();
    }








</body>
</html>

Areas/Admin/Views/Maintenance/addmaintenance.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Mvc;
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>

<html>

<head>

    <title>Add Maintenance Details</title>

    <link rel="stylesheet" href="~/css/add.css">

    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />

</head>

<body style=background-color:beige;>

    <script>
        function demobtn() {

            document.getElementById("number").value = "D11";
            document.getElementById("items").value = "Soaps, Newspapers, Magazines";

            document.getElementById("date3").value = "2020-10-02";
            document.getElementById("date4").value = "2020-10-19";

        }</script>

    <!--Added New-->
    <div class="nav-bar-rect">
        <div class="nav-bar-manager">
            <span>@HttpContextAccessor.HttpContext.Session.GetString("EIS_rendertype").Replace("\"", "")</span>
        </div>
    </div>
    <div class="nav-bar-profileName">
        <div class="dropdown">
            <button class="dropbtn">@(HttpContextAccessor.HttpContext.Session.GetString("EIS_eid").Replace("\"","") + " - "+ HttpContextAccessor.HttpContext.Session.GetString("EIS_ename").Replace("\"", ""))</button>
            <div class="dropdown-content">
                <a href="@Url.Action("userAcc", "Home", new { area = "Admin" })">Profile</a>
                <a href="@Url.Action("leave", "Home", new { area="Admin"})">Leave Form</a>
                <a href="@Url.Action("Logout", "Home", new { area = "Admin" })">Sign out</a>
            </div>
        </div>
    </div>
    <br>
    <!--End of Added-->
    <img src="~/img/des.png" align="right" width="500" height="400">


    <div class="row">
        <div class="col">
            <div class="form-group">
                <button class="btn btn-primary" id="demo" name="signup" onclick="demobtn()" style="background-color:purple">DEMO</button>

            </div>
        </div>
    </div>

    <div>
        @{ Html.BeginForm("Maintenance", "Mint", FormMethod.Post);
        }




        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">
                            <!-- <form action="/action_page.php">-->
                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="number">Room Number</label>
                                    <input type="text" class="form-control" id="number" name="RoomNo" placeholder="Enter the room number">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="number">Items need to be replaced : </label>

                                    <!---   <input type="checkbox" class="form-control" id="item1" name="item1" value="item1">
                <label for="vehicle1">Towels</label><br>
                <input type="checkbox" class="form-control" id="item2" name="item2" value="item2">
                <label for="vehicle2"> Flowers</label><br>
                <input type="checkbox" class="form-control" id="item3" name="item3" value="item3">
                <label for="vehicle3"> Magazines and Newspapers</label><br><br>
                -->

                                    <input type="text" class="form-control" id="items" name="Items" placeholder="Enter the items need to be replaced "><br>
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="number">Toiletries : </label>
                                    <!-- <input type="text" class="form-control" id="number" name="Toiletries" placeholder="Enter whether toiletries replaced or not"><br>
                -->

                                    <br>

                                    <input type="radio" id="number" name="Toiletries" value="Replaced">
                                    <label for="replace">Replaced</label><br>
                                    <input type="radio" id="number" name="Toiletries" value="Not Yet">
                                    <label for="other">Not Yet</label>




                                </div>
                            </div>




                            <p><u>Room Cleaning </u></p>
                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="date3">Last cleaned Date :</label><br><br>
                                    <input type="date" class="form-control" id="date3" name="LcleanDate" placeholder="Enter the last cleaned date"><br><br>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="date3">Next cleaning due Date :</label><br><br>
                                    <input type="date" class="form-control" id="date4" name="NcleanDate" placeholder="Enter the next cleaning due date"><br><br>
                                </div>
                            </div>
                        </div>






                        <input class="btn btn-primary" type="submit" value="Add Maintenance Details" name="add">
                        <br>
                        <!--Added-->
                        <a id="reqMTFromServer" href="@Url.Action("Maintenance", "Mint", new { area = "Admin" })" style="display:none"></a>
                        <script>
                            function reqMT() {
                                document.getElementById("reqMTFromServer").click();
                            }
                        </script>
                        <input class="btn btn-primary" onclick="reqMT()" type="button" value="View Maintenance Details" name="view">
                        <!--End-->
                        <br> <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @{Html.EndForm();
    }










</body>
</html>

Areas/Admin/Views/Maintenance/updateCustomer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>

<html>

<head>

    <title>Add Customer check-in Details</title>

    <link rel="stylesheet" href="~/css/add.css">

    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />

</head>

<body style=background-color:beige;>


    <br>

    <img src="~/img/des.png" align="right" width="500" height="400">

    <div>
        @{ Html.BeginForm(new { area = "Admin", controller = "Cus", action = "UpdateMint" });
        }
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">
                            <!-- <form action="/action_page.php">-->
                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="number">Customer ID</label>
                                    <input type="text" class="form-control" id="number" name="custId" value="@Model.custId" readonly>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="number">Customer Name</label>
                                    <input type="text" class="form-control" id="number" name="custName" value="@Model.custName">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="number">Room Number</label>
                                    <input type="text" class="form-control" id="number" name="RoomNo" value="@Model.RoomNo">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="number">Phone Number</label>
                                    <input type="text" class="form-control" id="number" name="phoneNo" value="@Model.phoneNo">
                                </div>
                            </div>



                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="date3">Check In Date :</label><br><br>
                                    <input type="date" class="form-control" id="date1" name="checkdate" value="@Model.checkdate" placeholder="Enter the check-in date"><br><br>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-9">
                                    <label for="date3">Check Out Date :</label><br><br>
                                    <input type="date" class="form-control" id="date2" name="checkOdate" value="@Model.checkOdate" placeholder="Enter the check-out date"><br><br>
                                </div>
                            </div>
                        </div>

                        <button class="btn btn-primary" type="submit" value="Update Customer Check-In Details" name="update">Update Maintenance Details</button>
                        <br>
                        @{Html.EndForm();
                        }



                    </div>
                </div>
            </div>
        </div>
    </div>










</body>
</html>